# Generated by Django 3.1.1 on 2020-09-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('publishedAt', models.TextField()),
                ('video_title', models.TextField(blank=True)),
                ('video_desc', models.TextField(blank=True)),
                ('thumbnail_url', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'VIDEOS',
            },
        ),
    ]
