# Generated by Django 3.1.1 on 2020-09-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_server_calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ABC',
            },
        ),
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
