# Generated by Django 3.1.1 on 2020-09-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_server_calls', '0004_auto_20200903_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'API_KEYS',
            },
        ),
        migrations.DeleteModel(
            name='abc',
        ),
        migrations.DeleteModel(
            name='videos',
        ),
    ]
